### ISSUE TITLE
Missing markers

### ISSUE THREAD

**Issue by Nyxtorm** [TechnicJelle/BlueMapFilteredEntities#13]
Hello,

Maybe I'm doing something wrong, but I can't get any marker on the map. I do have the toggle button, but for my test, no cow is displayed. No error during Blumap reload: `[BlueMapFilteredEntities] Loading filter set: cows`.

* Bluemap version: 5.3
* BlueMapFilteredEntities version: 1.0
* Spigot version: 1.21-R0.1-SNAPSHOT

My simple test filter with cows : 

```
filter-sets: {

    cows: {
        label: "Cows Test Filter"
        filters: [
            { type: cow }
        ]
    }

}
```

On my map, I should be able to see several cows here: 

![image](https://github.com/user-attachments/assets/01570213-6676-4155-8ee7-b9ec3fad48ac)

Sorry for my English.

**Comment by TechnicJelle** [comment]
Hi there! Thanks for trying my plugin! :)

Please note that this plugin does **not** support Spigot. Only [Paper](https://papermc.io/software/paper).

I just tried your config on my test server, and it seems to work:
![image](https://github.com/user-attachments/assets/69909439-1d7f-471f-a804-9fb8b19d6260)

Minecraft servers only load mobs in chunks that are loaded.
This plugin can't show mobs in unloaded chunks, due to that...¹
Try logging into the server and standing next to a cow, and seeing if it shows up?

1: Maybe I can solve that someday... I have an idea that might work...

**Comment by Nyxtorm** [comment]
Hi @TechnicJelle,

Yes, that was me doing something wrong. I migrated to PaperMC and no problem now.

Thank you for offering us all these tools and sorry for opening this issue for nothing! 😅

**Comment by TechnicJelle** [comment]
I'm glad to hear you've got it all working now! :D
