### ISSUE TITLE
Choose what information shows when you click on a marker

### ISSUE THREAD

**Issue by SkavenSkull** [TechnicJelle/BlueMapFilteredEntities#2]
Choose what information shows when you click on a marker

for example: remove UUID and location from the pop up

This could declutter the pop up and allow users full rein over what is displayed

![Screenshot 2024-05-21 185452](https://github.com/TechnicJelle/BlueMapFilteredEntities/assets/170445840/eeed240f-baec-4e0d-943c-3f2de3ce23a6)

**Comment by TechnicJelle** [comment]
How shall I make users format this in the config?
Like this:
```hocon
filters = [
  {
    type: minecart
    name: "Train"
    popup-info: [ type, name, custom-name ]
  }
]
```

Or shall I do it like this:
```hocon
filters = [
  {
    type: minecart
    name: "Train"
    popup-info-template: """
Entity type: {TYPE}
Name: {NAME}
Destination: {CUSTOM-NAME}
"""
  }
]
```
So you can choose the labels and formatting yourself?

Or maybe both? 
I'd rather not do both due to it being more effort, but I could see it being useful to have, like a simple option and an advanced option.

**Comment by TechnicJelle** [comment]
I went with the second one.
